//! Kryos extern declaration generator.
//!
//! Converts parsed C items into Kryos source text containing `extern "C"`
//! blocks, `@repr(C)` structs, `let` constants for enums and `#define`s.

use crate::c_parser::{CField, CItem, CParam, CType};

/// Generate Kryos source text from a list of parsed C items.
pub fn generate(items: &[CItem]) -> String {
    let mut out = String::new();
    out.push_str("// Generated by kryos bindgen\n");

    // Separate items by kind for grouped output
    let mut functions: Vec<&CItem> = Vec::new();
    let mut structs: Vec<&CItem> = Vec::new();
    let mut enums: Vec<&CItem> = Vec::new();
    let mut typedefs: Vec<&CItem> = Vec::new();
    let mut defines: Vec<&CItem> = Vec::new();

    for item in items {
        match item {
            CItem::Function { .. } => functions.push(item),
            CItem::Struct { .. } => structs.push(item),
            CItem::Enum { .. } => enums.push(item),
            CItem::Typedef { .. } => typedefs.push(item),
            CItem::Define { .. } => defines.push(item),
        }
    }

    // Extern functions block
    if !functions.is_empty() {
        out.push('\n');
        out.push_str("extern \"C\" {\n");
        for func in &functions {
            if let CItem::Function {
                name,
                params,
                ret_ty,
                variadic: _,
            } = func
            {
                out.push_str(&format!("    fn {name}("));
                // Emit non-variadic params (variadic `...` is dropped)
                let param_strs: Vec<String> = params
                    .iter()
                    .map(|p| format_param(p))
                    .collect();
                out.push_str(&param_strs.join(", "));
                out.push(')');
                // Return type
                let ret = map_type(ret_ty);
                if ret != "()" {
                    out.push_str(&format!(" -> {ret}"));
                }
                out.push('\n');
            }
        }
        out.push_str("}\n");
    }

    // Structs
    for item in &structs {
        if let CItem::Struct { name, fields } = item {
            out.push('\n');
            out.push_str("@repr(C)\n");
            out.push_str(&format!("struct {name} {{\n"));
            for (i, field) in fields.iter().enumerate() {
                let ty_str = map_type(&field.ty);
                out.push_str(&format!("    {}: {ty_str}", field.name));
                if i < fields.len() - 1 {
                    out.push(',');
                }
                out.push('\n');
            }
            out.push_str("}\n");
        }
    }

    // Typedefs (as type aliases)
    for item in &typedefs {
        if let CItem::Typedef { name, target } = item {
            let ty_str = map_type(target);
            out.push('\n');
            out.push_str(&format!("type {name} = {ty_str}\n"));
        }
    }

    // Enums as constants
    if !enums.is_empty() {
        out.push('\n');
        for item in &enums {
            if let CItem::Enum { name: _, variants } = item {
                for (vname, value) in variants {
                    let val = value.unwrap_or(0);
                    out.push_str(&format!("let {vname}: i32 = {val}\n"));
                }
            }
        }
    }

    // Defines as constants
    if !defines.is_empty() {
        out.push('\n');
        for item in &defines {
            if let CItem::Define { name, value } = item {
                let (ty, val) = infer_define_type(value);
                out.push_str(&format!("let {name}: {ty} = {val}\n"));
            }
        }
    }

    out
}

/// Format a single function parameter for Kryos output.
fn format_param(param: &CParam) -> String {
    let ty_str = map_type(&param.ty);
    match &param.name {
        Some(name) => format!("{name}: {ty_str}"),
        None => ty_str,
    }
}

/// Map a C type to its Kryos string representation.
pub fn map_type(ty: &CType) -> String {
    match ty {
        CType::Void => "()".to_string(),
        CType::Char | CType::UChar => "u8".to_string(),
        CType::Short => "i16".to_string(),
        CType::UShort => "u16".to_string(),
        CType::Int => "i32".to_string(),
        CType::UInt => "u32".to_string(),
        CType::Long | CType::LongLong => "i64".to_string(),
        CType::ULong | CType::ULongLong => "u64".to_string(),
        CType::Float => "f32".to_string(),
        CType::Double => "f64".to_string(),
        CType::SizeT => "usize".to_string(),
        CType::Bool => "bool".to_string(),
        CType::Pointer(inner) => {
            match inner.as_ref() {
                // void* -> *u8
                CType::Void => "*u8".to_string(),
                // char* / unsigned char* -> *u8
                CType::Char | CType::UChar => "*u8".to_string(),
                other => format!("*{}", map_type(other)),
            }
        }
        CType::Array(elem, size) => {
            let elem_str = map_type(elem);
            match size {
                Some(n) => format!("[{elem_str}; {n}]"),
                None => format!("*{elem_str}"),
            }
        }
        CType::Named(name) => name.clone(),
    }
}

/// Infer the Kryos type and value for a `#define` constant.
fn infer_define_type(value: &str) -> (&str, &str) {
    let v = value.trim();
    if v.starts_with('"') {
        return ("*u8", v);
    }
    if v.starts_with('\'') {
        return ("u8", v);
    }
    // Check for hex
    let num_str = v.strip_prefix('-').unwrap_or(v);
    if num_str.starts_with("0x") || num_str.starts_with("0X") {
        return ("i32", v);
    }
    // Check for float
    if v.contains('.') {
        return ("f64", v);
    }
    // Integer
    ("i32", v)
}

/// Map a C struct field to Kryos.
pub fn map_field(field: &CField) -> String {
    let ty_str = map_type(&field.ty);
    format!("{}: {ty_str}", field.name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_map_int() {
        assert_eq!(map_type(&CType::Int), "i32");
    }

    #[test]
    fn test_map_unsigned_int() {
        assert_eq!(map_type(&CType::UInt), "u32");
    }

    #[test]
    fn test_map_char_pointer() {
        assert_eq!(
            map_type(&CType::Pointer(Box::new(CType::Char))),
            "*u8"
        );
    }

    #[test]
    fn test_map_void_pointer() {
        assert_eq!(
            map_type(&CType::Pointer(Box::new(CType::Void))),
            "*u8"
        );
    }

    #[test]
    fn test_map_void() {
        assert_eq!(map_type(&CType::Void), "()");
    }

    #[test]
    fn test_map_double() {
        assert_eq!(map_type(&CType::Double), "f64");
    }

    #[test]
    fn test_map_size_t() {
        assert_eq!(map_type(&CType::SizeT), "usize");
    }

    #[test]
    fn test_map_bool() {
        assert_eq!(map_type(&CType::Bool), "bool");
    }

    #[test]
    fn test_map_long() {
        assert_eq!(map_type(&CType::Long), "i64");
    }

    #[test]
    fn test_map_long_long() {
        assert_eq!(map_type(&CType::LongLong), "i64");
    }

    #[test]
    fn test_map_unsigned_long() {
        assert_eq!(map_type(&CType::ULong), "u64");
    }

    #[test]
    fn test_map_float() {
        assert_eq!(map_type(&CType::Float), "f32");
    }

    #[test]
    fn test_map_short() {
        assert_eq!(map_type(&CType::Short), "i16");
    }

    #[test]
    fn test_map_named() {
        assert_eq!(map_type(&CType::Named("FILE".to_string())), "FILE");
    }

    #[test]
    fn test_generate_function() {
        let items = vec![CItem::Function {
            name: "puts".to_string(),
            params: vec![CParam {
                name: Some("s".to_string()),
                ty: CType::Pointer(Box::new(CType::Char)),
            }],
            ret_ty: CType::Int,
            variadic: false,
        }];
        let out = generate(&items);
        assert!(out.contains("extern \"C\" {"));
        assert!(out.contains("fn puts(s: *u8) -> i32"));
        assert!(out.contains("}"));
    }

    #[test]
    fn test_generate_struct() {
        let items = vec![CItem::Struct {
            name: "timeval".to_string(),
            fields: vec![
                CField {
                    name: "tv_sec".to_string(),
                    ty: CType::Long,
                },
                CField {
                    name: "tv_usec".to_string(),
                    ty: CType::Long,
                },
            ],
        }];
        let out = generate(&items);
        assert!(out.contains("@repr(C)"));
        assert!(out.contains("struct timeval {"));
        assert!(out.contains("tv_sec: i64"));
        assert!(out.contains("tv_usec: i64"));
    }

    #[test]
    fn test_generate_enum() {
        let items = vec![CItem::Enum {
            name: "color".to_string(),
            variants: vec![
                ("RED".to_string(), Some(0)),
                ("GREEN".to_string(), Some(1)),
                ("BLUE".to_string(), Some(2)),
            ],
        }];
        let out = generate(&items);
        assert!(out.contains("let RED: i32 = 0"));
        assert!(out.contains("let GREEN: i32 = 1"));
        assert!(out.contains("let BLUE: i32 = 2"));
    }

    #[test]
    fn test_generate_define() {
        let items = vec![CItem::Define {
            name: "EXIT_SUCCESS".to_string(),
            value: "0".to_string(),
        }];
        let out = generate(&items);
        assert!(out.contains("let EXIT_SUCCESS: i32 = 0"));
    }
}
