[package]
name = "kryos-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "kryos"
path = "src/main.rs"

[dependencies]
kryos-driver.workspace = true
kryos-errors.workspace = true
kryos-bindgen.workspace = true
kryos-doc.workspace = true
kryos-package.workspace = true
kryos-lsp.workspace = true
kryos-codegen-cranelift.workspace = true
kryos-codegen-llvm.workspace = true
kryos-test-runner.workspace = true
kryos-fmt.workspace = true
clap.workspace = true
