[package]
name = "kryos-driver"
version.workspace = true
edition.workspace = true

[dependencies]
kryos-errors.workspace = true
kryos-ast.workspace = true
kryos-lexer.workspace = true
kryos-parser.workspace = true
kryos-types.workspace = true
kryos-ownership.workspace = true
kryos-capabilities.workspace = true
kryos-mir.workspace = true
kryos-codegen-cranelift.workspace = true
kryos-codegen-llvm.workspace = true
kryos-linker.workspace = true
kryos-package.workspace = true
toml.workspace = true
