"""
CLI command handler for ``kryos bundle``.

Bundles a Kryos application into a self-contained deployment package
containing the compiled AST, launcher scripts (run.sh / run.bat), and a
Dockerfile for containerized deployment.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import stat
import sys
from dataclasses import fields, is_dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# ANSI helpers (mirror cli.py conventions)
# ---------------------------------------------------------------------------

_USE_COLOR = hasattr(sys.stdout, "isatty") and sys.stdout.isatty()


def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _USE_COLOR else text


def _red(t: str) -> str: return _c("31", t)
def _green(t: str) -> str: return _c("32", t)
def _yellow(t: str) -> str: return _c("33", t)
def _cyan(t: str) -> str: return _c("36", t)
def _bold(t: str) -> str: return _c("1", t)
def _dim(t: str) -> str: return _c("2", t)


# ---------------------------------------------------------------------------
# AST serialization
# ---------------------------------------------------------------------------

def _ast_to_dict(node: Any) -> Any:
    """Recursively convert a dataclass-based AST tree to plain dicts/lists."""
    if node is None:
        return None
    if isinstance(node, (str, int, float, bool)):
        return node
    if isinstance(node, list):
        return [_ast_to_dict(item) for item in node]
    if isinstance(node, tuple):
        return [_ast_to_dict(item) for item in node]
    if isinstance(node, dict):
        return {k: _ast_to_dict(v) for k, v in node.items()}
    if is_dataclass(node) and not isinstance(node, type):
        result: dict[str, Any] = {"_type": type(node).__name__}
        for f in fields(node):
            result[f.name] = _ast_to_dict(getattr(node, f.name))
        return result
    if hasattr(node, "value"):
        # Enum-like objects (e.g. token types stored on AST nodes)
        return str(node.value) if hasattr(node.value, "__str__") else repr(node)
    return repr(node)


# ---------------------------------------------------------------------------
# Launcher script templates
# ---------------------------------------------------------------------------

_RUN_SH_TEMPLATE = """\
#!/bin/bash
# Kryos application launcher
# Generated by: kryos bundle
# Date: {timestamp}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Prefer running from source via the Kryos interpreter
if command -v kryos >/dev/null 2>&1; then
    exec kryos run "$SCRIPT_DIR/{app_name}.kry" "$@"
fi

# Fallback: try python module invocation
if command -v python3 >/dev/null 2>&1; then
    exec python3 -m kryos.cli run "$SCRIPT_DIR/{app_name}.kry" "$@"
fi

echo "Error: kryos or python3 not found on PATH" >&2
echo "Install Kryos: pip install kryos-lang" >&2
exit 1
"""

_RUN_BAT_TEMPLATE = """\
@echo off
REM Kryos application launcher
REM Generated by: kryos bundle
REM Date: {timestamp}

set SCRIPT_DIR=%~dp0

where kryos >nul 2>&1
if %ERRORLEVEL% equ 0 (
    kryos run "%SCRIPT_DIR%{app_name}.kry" %*
    exit /b %ERRORLEVEL%
)

where python >nul 2>&1
if %ERRORLEVEL% equ 0 (
    python -m kryos.cli run "%SCRIPT_DIR%{app_name}.kry" %*
    exit /b %ERRORLEVEL%
)

echo Error: kryos or python not found on PATH >&2
echo Install Kryos: pip install kryos-lang >&2
exit /b 1
"""

_DOCKERFILE_TEMPLATE = """\
# Kryos application container
# Generated by: kryos bundle
# Date: {timestamp}

FROM python:3.12-slim AS runtime

WORKDIR /app

# Install the Kryos toolchain
RUN pip install --no-cache-dir kryos-lang 2>/dev/null || true

# Copy the bundled application
COPY {app_name}.kry /app/
COPY {app_name}.json /app/

# Default port (override with -p at docker run)
EXPOSE 8080

CMD ["kryos", "run", "{app_name}.kry"]
"""

_MANIFEST_TEMPLATE = """\
{{
  "name": "{app_name}",
  "version": "0.1.0",
  "kryos_version": "{kryos_version}",
  "source": "{source_name}",
  "ast": "{app_name}.json",
  "bundled_at": "{timestamp}",
  "target": "{target}",
  "release": {release}
}}
"""


# ---------------------------------------------------------------------------
# Bundle command implementation
# ---------------------------------------------------------------------------

def _run_bundle(args: argparse.Namespace) -> None:
    """Execute the ``kryos bundle`` command."""
    source = Path(args.source)

    if not source.exists():
        print(_red(f"error: source file not found: {source}"), file=sys.stderr)
        sys.exit(1)

    if source.suffix != ".kry":
        print(_red(f"error: expected .kry file, got '{source.suffix}'"), file=sys.stderr)
        sys.exit(1)

    output_dir = Path(args.output)
    app_name = source.stem
    target = args.target or ("windows-x64" if os.name == "nt" else "linux-x64")
    release = getattr(args, "release", False)

    print(_bold(f"Bundling {source} -> {output_dir}/"))
    print()

    # ------------------------------------------------------------------
    # Step 1: Compile source to AST
    # ------------------------------------------------------------------
    from kryos.compiler import tokenize, parse, LexerError, ParseError
    from kryos.compiler.parser import ParseErrors

    source_code = source.read_text(encoding="utf-8")

    try:
        tokens = tokenize(source_code, str(source))
    except LexerError as e:
        print(_red(f"Lexer error: {e}"), file=sys.stderr)
        sys.exit(1)

    try:
        module = parse(tokens)
    except (ParseError, ParseErrors) as e:
        print(_red(f"Parse error: {e}"), file=sys.stderr)
        sys.exit(1)

    # ------------------------------------------------------------------
    # Step 2: Create output directory and write artifacts
    # ------------------------------------------------------------------
    output_dir.mkdir(parents=True, exist_ok=True)

    # 2a: Write AST JSON
    ast_dict = _ast_to_dict(module)
    ast_json = json.dumps(ast_dict, indent=2)
    ast_path = output_dir / f"{app_name}.json"
    ast_path.write_text(ast_json, encoding="utf-8")
    print(f"  {_green('AST')}        {ast_path} ({len(ast_json):,} bytes)")

    # 2b: Copy source file
    dest_source = output_dir / source.name
    shutil.copy2(str(source), str(dest_source))
    print(f"  {_green('Source')}     {dest_source}")

    # 2c: Timestamp for generated files
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    from kryos import __version__ as kryos_version

    # 2d: Write launcher scripts
    run_sh = output_dir / "run.sh"
    run_sh.write_text(
        _RUN_SH_TEMPLATE.format(app_name=app_name, timestamp=timestamp),
        encoding="utf-8",
    )
    # Make run.sh executable (no-op on Windows but correct for the artifact)
    try:
        run_sh.chmod(run_sh.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError:
        pass  # Windows may not support chmod; that's fine
    print(f"  {_green('Launcher')}   {run_sh}")

    run_bat = output_dir / "run.bat"
    run_bat.write_text(
        _RUN_BAT_TEMPLATE.format(app_name=app_name, timestamp=timestamp),
        encoding="utf-8",
    )
    print(f"  {_green('Launcher')}   {run_bat}")

    # 2e: Write Dockerfile
    dockerfile = output_dir / "Dockerfile"
    dockerfile.write_text(
        _DOCKERFILE_TEMPLATE.format(app_name=app_name, timestamp=timestamp),
        encoding="utf-8",
    )
    print(f"  {_green('Docker')}     {dockerfile}")

    # 2f: Write bundle manifest
    manifest_path = output_dir / "bundle.json"
    manifest_path.write_text(
        _MANIFEST_TEMPLATE.format(
            app_name=app_name,
            kryos_version=kryos_version,
            source_name=source.name,
            timestamp=timestamp,
            target=target,
            release=str(release).lower(),
        ),
        encoding="utf-8",
    )
    print(f"  {_green('Manifest')}   {manifest_path}")

    # ------------------------------------------------------------------
    # Step 3: Summary
    # ------------------------------------------------------------------
    print()
    print(_green(f"Bundle complete: {output_dir}/"))
    print()
    print(_bold("Run locally:"))
    print(f"  {_cyan('./'+str(output_dir)+'/run.sh')}          {_dim('# Linux / macOS')}")
    print(f"  {_cyan(str(output_dir)+ chr(92) +'run.bat')}           {_dim('# Windows')}")
    print()
    print(_bold("Run with Docker:"))
    print(f"  {_cyan(f'cd {output_dir} && docker build -t {app_name} . && docker run -p 8080:8080 {app_name}')}")


# ---------------------------------------------------------------------------
# Registration -- called from cli.py
# ---------------------------------------------------------------------------

def register_bundle_command(subparsers: argparse._SubParsersAction) -> dict[str, Any]:
    """Register the ``bundle`` subcommand.

    Returns a dict mapping command name -> handler function, matching the
    pattern used by ``register_package_commands``.
    """
    p = subparsers.add_parser(
        "bundle",
        help="Bundle a Kryos app into a deployable package",
    )
    p.add_argument("source", help="Source .kry file to bundle")
    p.add_argument(
        "-o", "--output",
        default="dist",
        help="Output directory (default: dist)",
    )
    p.add_argument(
        "--target",
        default=None,
        choices=["linux-x64", "linux-arm64", "windows-x64"],
        help="Target platform (default: auto-detect)",
    )
    p.add_argument(
        "--release",
        action="store_true",
        help="Strip debug spans from AST for smaller bundle",
    )

    return {"bundle": _run_bundle}
