//! Integration tests for kryos-bindgen.

use kryos_bindgen::c_parser::{parse_c_header, CItem, CType};
use kryos_bindgen::generate_bindings;

// ---------------------------------------------------------------------------
// C parser tests
// ---------------------------------------------------------------------------

#[test]
fn parse_function_puts() {
    let items = parse_c_header("int puts(const char* s);").unwrap();
    assert_eq!(items.len(), 1);
    match &items[0] {
        CItem::Function {
            name,
            params,
            ret_ty,
            variadic,
        } => {
            assert_eq!(name, "puts");
            assert_eq!(*ret_ty, CType::Int);
            assert!(!variadic);
            assert_eq!(params.len(), 1);
            assert_eq!(params[0].ty, CType::Pointer(Box::new(CType::Char)));
            assert_eq!(params[0].name, Some("s".to_string()));
        }
        other => panic!("expected Function, got {other:?}"),
    }
}

#[test]
fn parse_struct_timeval() {
    let items = parse_c_header("struct timeval { long tv_sec; long tv_usec; };").unwrap();
    assert_eq!(items.len(), 1);
    match &items[0] {
        CItem::Struct { name, fields } => {
            assert_eq!(name, "timeval");
            assert_eq!(fields.len(), 2);
            assert_eq!(fields[0].name, "tv_sec");
            assert_eq!(fields[0].ty, CType::Long);
            assert_eq!(fields[1].name, "tv_usec");
            assert_eq!(fields[1].ty, CType::Long);
        }
        other => panic!("expected Struct, got {other:?}"),
    }
}

#[test]
fn parse_enum_color() {
    let items = parse_c_header("enum color { RED = 0, GREEN = 1 };").unwrap();
    assert_eq!(items.len(), 1);
    match &items[0] {
        CItem::Enum { name, variants } => {
            assert_eq!(name, "color");
            assert_eq!(variants.len(), 2);
            assert_eq!(variants[0], ("RED".to_string(), Some(0)));
            assert_eq!(variants[1], ("GREEN".to_string(), Some(1)));
        }
        other => panic!("expected Enum, got {other:?}"),
    }
}

#[test]
fn parse_typedef_uint32() {
    let items = parse_c_header("typedef unsigned int uint32_t;").unwrap();
    assert_eq!(items.len(), 1);
    match &items[0] {
        CItem::Typedef { name, target } => {
            assert_eq!(name, "uint32_t");
            assert_eq!(*target, CType::UInt);
        }
        other => panic!("expected Typedef, got {other:?}"),
    }
}

#[test]
fn parse_define_exit_success() {
    let items = parse_c_header("#define EXIT_SUCCESS 0").unwrap();
    assert_eq!(items.len(), 1);
    match &items[0] {
        CItem::Define { name, value } => {
            assert_eq!(name, "EXIT_SUCCESS");
            assert_eq!(value, "0");
        }
        other => panic!("expected Define, got {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// Generator tests
// ---------------------------------------------------------------------------

#[test]
fn generate_simple_function() {
    let src = "int puts(const char* s);";
    let out = generate_bindings(src).unwrap();
    assert!(out.contains("// Generated by kryos bindgen"));
    assert!(out.contains("extern \"C\" {"));
    assert!(out.contains("fn puts(s: *u8) -> i32"));
    assert!(out.contains("}"));
}

#[test]
fn generate_struct_repr_c() {
    let src = "struct timeval { long tv_sec; long tv_usec; };";
    let out = generate_bindings(src).unwrap();
    assert!(out.contains("@repr(C)"));
    assert!(out.contains("struct timeval {"));
    assert!(out.contains("tv_sec: i64"));
    assert!(out.contains("tv_usec: i64"));
}

#[test]
fn generate_enum_constants() {
    let src = "enum color { RED = 0, GREEN = 1, BLUE = 2 };";
    let out = generate_bindings(src).unwrap();
    assert!(out.contains("let RED: i32 = 0"));
    assert!(out.contains("let GREEN: i32 = 1"));
    assert!(out.contains("let BLUE: i32 = 2"));
}

// ---------------------------------------------------------------------------
// Combined / edge-case tests
// ---------------------------------------------------------------------------

#[test]
fn full_header_mixed_items() {
    let src = r#"
#include <stdio.h>

// A comment
#define MAX_SIZE 1024

typedef unsigned long size_t;

struct point {
    int x;
    int y;
};

enum direction { NORTH = 0, SOUTH = 1, EAST = 2, WEST = 3 };

int puts(const char* s);
void* malloc(size_t size);
int printf(const char* fmt, ...);
"#;
    let out = generate_bindings(src).unwrap();

    // Functions
    assert!(out.contains("fn puts(s: *u8) -> i32"));
    assert!(out.contains("fn malloc(size: usize) -> *u8"));
    assert!(out.contains("fn printf(fmt: *u8) -> i32")); // variadic params dropped

    // Struct
    assert!(out.contains("@repr(C)"));
    assert!(out.contains("struct point {"));
    assert!(out.contains("x: i32"));
    assert!(out.contains("y: i32"));

    // Enum constants
    assert!(out.contains("let NORTH: i32 = 0"));
    assert!(out.contains("let SOUTH: i32 = 1"));
    assert!(out.contains("let EAST: i32 = 2"));
    assert!(out.contains("let WEST: i32 = 3"));

    // Define
    assert!(out.contains("let MAX_SIZE: i32 = 1024"));

    // Typedef
    assert!(out.contains("type size_t = u64"));
}

#[test]
fn ignore_comments_and_includes() {
    let src = r#"
// Single line comment
/* Block comment
   spanning multiple lines */
#include <stdlib.h>
#include "myheader.h"
#ifdef _WIN32
#endif
int foo(void);
"#;
    let out = generate_bindings(src).unwrap();
    assert!(out.contains("fn foo()"));
    // Should not contain any include or ifdef artifacts
    assert!(!out.contains("#include"));
    assert!(!out.contains("#ifdef"));
}

#[test]
fn handle_const_pointer_types() {
    let src = "int strcmp(const char* s1, const char* s2);";
    let out = generate_bindings(src).unwrap();
    assert!(out.contains("fn strcmp(s1: *u8, s2: *u8) -> i32"));
}

#[test]
fn handle_void_pointer_to_u8_ptr() {
    let src = "void free(void* ptr);";
    let out = generate_bindings(src).unwrap();
    assert!(out.contains("fn free(ptr: *u8)"));
    // void return should not show `-> ()`
    assert!(!out.contains("-> ()"));
}

#[test]
fn variadic_function_drops_ellipsis() {
    let src = "int sprintf(char* buf, const char* fmt, ...);";
    let items = parse_c_header(src).unwrap();
    assert_eq!(items.len(), 1);
    match &items[0] {
        CItem::Function {
            name,
            params,
            variadic,
            ..
        } => {
            assert_eq!(name, "sprintf");
            assert!(*variadic);
            // Only the named params, not `...`
            assert_eq!(params.len(), 2);
        }
        other => panic!("expected Function, got {other:?}"),
    }

    let out = generate_bindings(src).unwrap();
    // The generated output should contain only the non-variadic params
    assert!(out.contains("fn sprintf(buf: *u8, fmt: *u8) -> i32"));
    assert!(!out.contains("..."));
}

#[test]
fn typedef_pointer() {
    let src = "typedef void* HANDLE;";
    let items = parse_c_header(src).unwrap();
    assert_eq!(items.len(), 1);
    match &items[0] {
        CItem::Typedef { name, target } => {
            assert_eq!(name, "HANDLE");
            assert_eq!(*target, CType::Pointer(Box::new(CType::Void)));
        }
        other => panic!("expected Typedef, got {other:?}"),
    }
}

#[test]
fn define_hex_constant() {
    let src = "#define MAGIC 0xFF00";
    let items = parse_c_header(src).unwrap();
    assert_eq!(items.len(), 1);
    match &items[0] {
        CItem::Define { name, value } => {
            assert_eq!(name, "MAGIC");
            assert_eq!(value, "0xFF00");
        }
        other => panic!("expected Define, got {other:?}"),
    }
}

#[test]
fn define_string_constant() {
    let src = r#"#define VERSION "1.0.0""#;
    let items = parse_c_header(src).unwrap();
    assert_eq!(items.len(), 1);
    match &items[0] {
        CItem::Define { name, value } => {
            assert_eq!(name, "VERSION");
            assert_eq!(value, "\"1.0.0\"");
        }
        other => panic!("expected Define, got {other:?}"),
    }
}

#[test]
fn function_returning_void() {
    let src = "void exit(int status);";
    let out = generate_bindings(src).unwrap();
    assert!(out.contains("fn exit(status: i32)"));
    assert!(!out.contains("fn exit(status: i32) ->"));
}

#[test]
fn struct_with_pointer_field() {
    let src = "struct node { int value; struct node* next; };";
    let items = parse_c_header(src).unwrap();
    match &items[0] {
        CItem::Struct { name, fields } => {
            assert_eq!(name, "node");
            assert_eq!(fields.len(), 2);
            assert_eq!(fields[0].ty, CType::Int);
            assert_eq!(
                fields[1].ty,
                CType::Pointer(Box::new(CType::Named("node".to_string())))
            );
        }
        other => panic!("expected Struct, got {other:?}"),
    }
}

#[test]
fn enum_without_values() {
    let src = "enum status { OK, ERR };";
    let items = parse_c_header(src).unwrap();
    match &items[0] {
        CItem::Enum { name, variants } => {
            assert_eq!(name, "status");
            assert_eq!(variants[0], ("OK".to_string(), None));
            assert_eq!(variants[1], ("ERR".to_string(), None));
        }
        other => panic!("expected Enum, got {other:?}"),
    }
}

#[test]
fn multiple_functions_in_extern_block() {
    let src = r#"
int open(const char* path, int flags);
int close(int fd);
long read(int fd, void* buf, unsigned long count);
"#;
    let out = generate_bindings(src).unwrap();
    assert!(out.contains("fn open(path: *u8, flags: i32) -> i32"));
    assert!(out.contains("fn close(fd: i32) -> i32"));
    assert!(out.contains("fn read(fd: i32, buf: *u8, count: u64) -> i64"));
}

#[test]
fn bool_type() {
    let src = "bool is_valid(int x);";
    let items = parse_c_header(src).unwrap();
    match &items[0] {
        CItem::Function { ret_ty, .. } => {
            assert_eq!(*ret_ty, CType::Bool);
        }
        other => panic!("expected Function, got {other:?}"),
    }
    let out = generate_bindings(src).unwrap();
    assert!(out.contains("-> bool"));
}

#[test]
fn size_t_param() {
    let src = "void* memcpy(void* dest, const void* src, size_t n);";
    let out = generate_bindings(src).unwrap();
    assert!(out.contains("fn memcpy(dest: *u8, src: *u8, n: usize) -> *u8"));
}
