; Kryos LLVM IR -- generated by the Kryos compiler
; Module: <main>
target triple = "x86_64-pc-linux-gnu"

declare i32 @puts(i8*)
@.str.0 = private unnamed_addr constant [14 x i8] c"Hello, Kryos!\00"
declare i32 @printf(i8*, ...)
@.str.1 = private unnamed_addr constant [6 x i8] c"%d\5C0A\00"
@.str.2 = private unnamed_addr constant [6 x i8] c"%f\5C0A\00"

define i32 @main() {
entry:
  %0 = getelementptr [14 x i8], [14 x i8]* @.str.0, i32 0, i32 0
  %1 = call i32 @puts(i8* %0)
  %2 = getelementptr [4 x i8], [4 x i8]* @.str.1, i32 0, i32 0
  %3 = call i32 (i8*, ...) @printf(i8* %2, i32 42)
  %4 = getelementptr [4 x i8], [4 x i8]* @.str.2, i32 0, i32 0
  %5 = call i32 (i8*, ...) @printf(i8* %4, double 3.140000e+00)
  %6 = getelementptr [4 x i8], [4 x i8]* @.str.1, i32 0, i32 0
  %7 = call i32 (i8*, ...) @printf(i8* %6, i32 1)
  %8 = getelementptr [4 x i8], [4 x i8]* @.str.1, i32 0, i32 0
  %9 = call i32 (i8*, ...) @printf(i8* %8, i32 0)
  ret i32 0
}

