//! Generates a complete (symbol name -> fn pointer) inventory of every
//! `#[no_mangle] extern "C"` function in this crate.
//!
//! The Cranelift JIT (the `kryos test` runner; `kryos run` is AOT + a
//! subprocess) must register every native symbol explicitly -- the AOT path
//! resolves them at link time against the staticlib, so a symbol missing from
//! the JIT's hand-maintained list produced no error anywhere until a test
//! actually imported the module, then aborted with cranelift-jit's
//! "can't resolve symbol kryos_db_open" panic. Generating the inventory from
//! the sources ends that drift class: a new native is registered the moment
//! it is written.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let src_dir = manifest.join("src");
    println!("cargo:rerun-if-changed={}", src_dir.display());

    // Feature-gated modules (`#[cfg(feature = "x")] pub mod y;` in lib.rs)
    // only exist when the feature is on; skip their symbols otherwise or the
    // generated paths fail to compile. Cargo exposes active features to
    // build scripts as CARGO_FEATURE_<NAME>.
    let lib_src = fs::read_to_string(src_dir.join("lib.rs")).unwrap_or_default();
    let mut gated_off: std::collections::HashSet<String> = std::collections::HashSet::new();
    {
        let lines: Vec<&str> = lib_src.lines().collect();
        for (i, line) in lines.iter().enumerate() {
            let t = line.trim();
            if let Some(feat) = t
                .strip_prefix("#[cfg(feature = \"")
                .and_then(|r| r.split('"').next())
            {
                let feat_env = format!(
                    "CARGO_FEATURE_{}",
                    feat.to_uppercase().replace('-', "_")
                );
                if env::var(feat_env).is_err() {
                    if let Some(next) = lines.get(i + 1) {
                        if let Some(m) = next
                            .trim()
                            .strip_prefix("pub mod ")
                            .and_then(|r| r.strip_suffix(';'))
                        {
                            gated_off.insert(m.to_string());
                        }
                    }
                }
            }
        }
    }

    let mut entries: Vec<(String, String)> = Vec::new(); // (fn name, module)
    let mut seen = std::collections::HashSet::new();
    if let Ok(files) = fs::read_dir(&src_dir) {
        for entry in files.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                continue;
            }
            let Some(module) = path.file_stem().and_then(|s| s.to_str()).map(String::from)
            else {
                continue;
            };
            if module == "lib" || gated_off.contains(&module) {
                continue;
            }
            let Ok(src) = fs::read_to_string(&path) else {
                continue;
            };
            let lines: Vec<&str> = src.lines().collect();
            for (i, line) in lines.iter().enumerate() {
                if !line.trim_start().starts_with("#[no_mangle]") {
                    continue;
                }
                // The `extern "C" fn NAME` header follows within a few lines
                // (possibly after more attributes / cfg gates).
                for follow in lines.iter().skip(i + 1).take(5) {
                    if let Some(pos) = follow.find("extern \"C\" fn ") {
                        let rest = &follow[pos + "extern \"C\" fn ".len()..];
                        let name: String = rest
                            .chars()
                            .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                            .collect();
                        // cfg(unix)/cfg(not(unix)) variants define the same
                        // name twice -- register once (same module path
                        // resolves whichever variant is compiled in).
                        if !name.is_empty() && seen.insert(name.clone()) {
                            entries.push((name, module.clone()));
                        }
                        break;
                    }
                }
            }
        }
    }
    entries.sort();

    let mut out = String::from(
        "/// Every #[no_mangle] extern \"C\" symbol in this crate, generated by\n\
         /// build.rs for bulk JIT registration. See build.rs for why.\n\
         pub fn native_symbols() -> Vec<(&'static str, *const u8)> {\n    vec![\n",
    );
    for (name, module) in &entries {
        out.push_str(&format!(
            "        ({name:?}, crate::{module}::{name} as *const u8),\n"
        ));
    }
    out.push_str("    ]\n}\n");

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("native_symbols.rs");
    fs::write(dest, out).unwrap();
}
