[package]
name = "kryos-stdlib-native"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]

[features]
default = ["crypto", "sqlite", "tls", "postgres", "http2"]
crypto = ["ring"]
sqlite = ["rusqlite"]
tls = ["rustls", "rustls-pemfile", "rustls-pki-types", "webpki-roots"]
postgres = ["dep:postgres", "dep:postgres-native-tls", "dep:native-tls"]
http2 = ["dep:reqwest"]

[dependencies]
kryos-rt.workspace = true
ring = { workspace = true, optional = true }
rusqlite = { workspace = true, optional = true }
rustls = { workspace = true, optional = true }
rustls-pemfile = { workspace = true, optional = true }
rustls-pki-types = { workspace = true, optional = true }
webpki-roots = { workspace = true, optional = true }
postgres = { workspace = true, optional = true }
postgres-native-tls = { workspace = true, optional = true }
native-tls = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
regex.workspace = true
crossterm.workspace = true
base64 = "0.22"
